theme: null

author: "Vitalii Radzividlo"
description: "This is a portfolio website created with jekyll from scratch" 
title: "My Portfolio"
email: "myEmail@mail.com"

baseurl: "" # Leave blank for GitHub Pages root
url: "https://Veentikon.github.io" # Your website URL


sass:
  sass_dir: assets/_scss
  css_dir: assets/css

