author: "Vitalii Radzividlo"
description: "This is a portfolio website created with jekyll from scratch" 
title: "this is a title"
email: "myEmail@mail.com"
background-image: "jeremy-bishop-G9i_plbfDgk-unsplash.jpg"

baseurl: "" # Leave blank for GitHub Pages root
url: "https://Veentikon.github.io" # Your website URL
